version: '3'
services:
  server:
    build: ./server/
    ports:
     - "3000:3000"
  web:
    build: ./client/
    ports:
    - "80:80"
  redis:
    image: "redis:alpine"
    ports: 
      - "6379:6379"